# TODO: Translation updated at 2023-11-28 19:32

translate Spanish strings:

    # game/screens_cast.rpy:1123
    old "{i}\"Everything has kept going on without me, and changed so much.\"{/i}\n                                "
    new "{i}\"Todo ha seguido adelante sin mí, y ha cambiado mucho.\"{/i}\n                                "

    # game/screens_cast.rpy:1128
    old "Born in 1895 to a farming family in Ach-na-Creige, Scotland, Malcolm Campbell has always held a serene demeanor and a deep heart. Even as a wee bairn, hardly ever did a cry spill from his lips. A strong student—motivated to learn all subjects—Campbell was encouraged by his teacher to attend college in Glasgow. But the world had other plans.\n\nIn the midst of the Great War, Campbell enlisted in the Royal Scots Greys, leaving home for the first time at the age of 19. His first steps out of his village led him into the darkest of times, the most desperate of experiences.\n\nAfter surviving the horrors of war, Campbell once again returned home. There, he cares for his Gran, and has fallen back into his role as farmer. Still friendly, dependable, honorable, and brave, Campbell has become more reserved towards locals, even as he is welcomed back home. His life moves forward with the goals of providing for his grandmother, ensuring the prosperity of his land, and living a life that gives him meaning and purpose.\n                                "
    new "Nacido en 1895 en una familia de agricultores en Ach-na-Creige, Escocia, Malcolm Campbell siempre ha tenido una conducta serena y un gran corazón. Incluso cuando era un niño, casi nunca se le escapaba un grito de los labios. Un estudiante fuerte, motivado por aprender todas las materias, Campbell fue animado por su maestro a asistir a la universidad en Glasgow, pero el mundo tenía otros planes.\n\nEn medio de la Gran Guerra, Campbell se alistó en los Royal Scots Greys y abandonó su hogar por primera vez. vez a la edad de 19 años. Sus primeros pasos fuera de su aldea lo llevaron a los tiempos más oscuros, a las experiencias más desesperadas.\n\nDespués de sobrevivir a los horrores de la guerra, Campbell volvió a casa. Allí, se preocupa por su Abue, y ha vuelto a asumir su papel de granjero. Aún amigable, confiable, honorable y valiente, Campbell se ha vuelto más reservado con los lugareños, incluso cuando es bienvenido en casa. Su vida continua con sus nuevos objetivos, mantener a su abuela, garantizar la prosperidad de su tierra y vivir una vida que le dé significado y propósito.\n                                "

    # game/screens_cast.rpy:1767
    old "Enable\nAdult Content\nfor More"
    new "Activar\nContenido para adultos\npara más"

    # game/screens_cast.rpy:2506
    old "{i}\"You have friends still. They're here.\nI'm here.\"{/i}\n                                "
    new "{i}\"Todavia tienes amigos. Estan aquí.\nYo estoy aquí.\"{/i}\n                                "

    # game/screens_cast.rpy:2512
    old "The eldest of the three MacLeod sisters, Marion always wanted to make her father proud.  Growing up she did her best to keep the farm running, the house in shape, and her sisters out of trouble.  It wasn't easy, but it kindled the dream of living a normal, domestic life.\n\nWith their father now away at war Marion finds it more difficult to be the glue that holds her family together.  She feels like she has already lost Jessie and is worried she will lose Grace too.  But she would be the last person to admit she needs help.\n\nLittle does she know, things are about to get a lot more complicated...\n                                "
    new "Marion, la mayor de las tres hermanas MacLeod, siempre quiso enorgullecer a su padre. Al crecer, hizo todo lo posible para mantener la granja en funcionamiento, la casa en orden y que sus hermanas no se metieran en problemas. No fue fácil, pero encendió el sueño de vivir una vida doméstica normal.\n\nCon su padre ahora lejos debido a la guerra, a Marion le resulta más difícil ser el pegamento que mantiene unida a su familia. Siente que ya ha perdido a Jessie y le preocupa perder también a Grace. Pero ella sería la última persona en admitir que necesita ayuda.\n\nLo que no sabe es que las cosas están a punto de ponerse mucho más complicadas...\n                                "

    # game/screens_cast.rpy:4500
    old "{i}\"I've got big plans, mister. You've never met a more determined girl!\"{/i}\n                                "
    new "{i}\"Tengo grandes planes, señor. Nunca conocera a una chica más determinada!\"{/i}\n                                "

    # game/screens_cast.rpy:4505
    old "The middle MacLeod sister, Jessie, was never much one for rules.  She wanted to live fast and free.  Humdrum country life, and the rest of her family's embrace of it, chafed at her to no end.\n\nNow with most of the men off to war, Jessie seized the chance to finally flaunt her freedom like she always wanted.  She dressed like the flappers in Glasgow and listened to the Yanks' new jazz sounds.  But it wasn't enough, not so long as she stayed stuck in Ach-na-Creige.  Jessie had to move to the city.\n\nShe works at the local pub, whose patrons don't know quite what to make of the misfit.  But once she's scraped together enough schillings, what they think won't matter.  She is leaving and never looking back.  What's to stop her?\n                                "
    new "La hermana de en medio MacLeod, Jessie, nunca fue muy partidaria de las reglas. Quería vivir rápido y libre. La monótona vida rural y la aceptación de ella por parte del resto de su familia la irritaban muchísimo.\n\nAhora que la mayoría de los hombres se fueron a la guerra, Jessie aprovechó la oportunidad para finalmente hacer alarde de su libertad como siempre quiso. Se vestía como las flappers de Glasgow y escuchaba los nuevos sonidos del jazz de los Yankees. Pero no era suficiente, mientras ella permaneciera atrapada en Ach-na-Creige. Jessie tenía que mudarse a la ciudad.\n\nTrabaja en la taberna local, cuyos clientes no saben muy bien qué pensar de la inadaptada. Pero una vez que haya reunido suficientes chelines, lo que piensen no importará. Ella se irá sin mirar atrás. ¿Qué puede detenerla?\n                                "

    # game/screens_cast.rpy:6924
    old "{i}\"I'll go wherever the currents take me.\"{/i}\n                                "
    new "{i}\"Ire a donde sea que las corrientes me lleven\"{/i}\n                                "

    # game/screens_cast.rpy:6929
    old "Grace is the youngest of the three MacLeod sisters, and the most reserved.  Events from her childhood left her feeling cautious toward her father, her sisters, and everyone else. She never really felt like part of a group, prefering to withdraw from social activities and spend time alone among nature.\n\nNow that the sisters are on their own, Grace has conceded to help Marion around the farm—at least, when it suits her. One might have better luck finding Grace riding in the vales, or taking a dip in her favorite swimming hole.  That is, of course, if she wants to be found.\n\nWhile Grace strives to keep to herself, she might soon find herself a new friend; one who will fulfill dreams she didn't even know she had. Big dreams, with even bigger consequences...\n                                "
    new "Grace es la menor de las tres hermanas MacLeod y la más reservada. Los acontecimientos de su infancia la hicieron ser cautelosa hacia su padre, sus hermanas y todos los demás. En realidad nunca se sintió parte de un grupo, prefiriendo retirarse de las actividades sociales y pasar tiempo sola entre la naturaleza.\n\nAhora que las hermanas están solas, Grace ha aceptado ayudar a Marion en la granja, al menos, cuando le apetece. Uno podría tener más suerte al encontrar a Grace cabalgando por los valles o dándose un chapuzón en su poza favorita para nadar. Eso, por supuesto, si quiere que la encuentren.\n\nAunque Grace se esfuerza por mantenerse reservada, pronto podría encontrar una nueva amigo; uno que cumplirá sueños que ni siquiera sabía que tenía. Grandes sueños, con consecuencias aún mayores...\n                                "

    # game/screens_cast.rpy:8471
    old "{i}\"If you need me, I'll be here.\nBut we can't avoid our fates, Malcolm.\"{/i}\n                                "
    new "{i}\"Estare aquí si me necesitas\nPero no podemos evitar nuestros destinos, Malcolm.\"{/i}\n                                "

    # game/screens_cast.rpy:8476
    old "Effie isn't from around here, is she? She keeps turning up at the oddest times, and seems to know just a little too much. There's definitely something strange about this girl.\n\nTimid and skittish, it is hard to corner Effie for a conversation unless there is no one else around. But those who get to know her will discover that she has a heart of gold. Loyal, friendly and helpful—in her own quiet way—Effie is a blessing to those who are closest to her.\n\nJust be careful, because getting to know her too well could lead down a rabbit hole—and a very deep one at that!\n                                "
    new "Effie no es de por aquí, ¿verdad? Sigue apareciendo en los momentos más extraños y parece saber demasiado. Definitivamente hay algo extraño en esta chica.\n\nTímida y asustadiza, es difícil arrinconar a Effie para conversar a menos que no haya nadie más cerca. Pero quienes la conozcan descubrirán que tiene un corazón de oro. Leal, amigable y servicial (a su sutil manera), Effie es una bendición para quienes están más cerca de ella.\n\nSolo ten cuidado, porque llegar a conocerla demasiado bien podría llevarte a una madriguera de conejo, y una muy profunda.\n                                "

    # game/screens_cast.rpy:8689
    old "{i}\"Neigh.\"{/i}"
    new "{i}\*Relincho\*{/i}"

    # game/screens_cast.rpy:8693
    old "Despite her winsome gaze and regal stature, Hazel is just a grump at heart. After Malcolm purchases the mare at auction (at a discount no less), he discovers her grouchiness is a bit of a challenge. While her history is unknown to her new master, he finds ways to develop a strong rapport with his sassy sidekick.\n\nShe finds her new life in Ach-na-Creige a bit curious, and enjoys giving others a glimpse of her churlish nature by bucking, neighing and being disobedient. Thankfully, a good deal of her irascible attitude can be appeased with carrots and apples. She definitely responds more favorably to wildflowers than whips.\n\nHazel’s charm comes from her headstrong and rebellious behavior. After all, she’s not unlike other women of Ach-na-Creige: strong, stubborn, independent, and endearing.\n                                "
    new "A pesar de su mirada encantadora y su gran estatura, Hazel es simplemente una gruñona en el fondo. Después de que Malcolm comprase a la yegua en una subasta (nada menos que con un descuento), descubre que su mal humor es todo un desafío. Si bien su nuevo maestro desconoce su historia, él encuentra formas de desarrollar una fuerte relación con su atrevida compañera.\n\nSu nueva vida en Ach-na-Creige le resulta un poco curiosa y disfruta dando a los demás un vistazo de su grosera naturaleza al resistirse, relinchar y ser desobediente. Afortunadamente, gran parte de su actitud irascible se puede apaciguar con zanahorias y manzanas. Definitivamente responde más favorablemente a las flores silvestres que a los látigos.\n\nEl encanto de Hazel proviene de su comportamiento testarudo y rebelde. Después de todo, no es tan diferente de otras mujeres de Ach-na-Creige: fuerte, testaruda, independiente y entrañable.\n                                "

    # game/screens_cast.rpy:8903
    old "{i}\"Don't get too close to them.\nKnow you've been asked in earnest.\nPlease stay away from the MacLeods.\"{/i}\n                                "
    new "{i}\"No te les acerques demasiado\nDebes saber que lo digo en serio\nPor favor alejate de las MacLeod.\"{/i}\n                                "

    # game/screens_cast.rpy:8909
    old "Born and raised in Ach-na-Creige, Alana Urquhart is a permanent fixture in the town. Everyone's favorite—and only—schoolteacher, she is at once strict and loving toward the young lads and lasses under her care. Meanwhile, Alana's eccentricities have given her an odd reputation among former students who've grown up. Some go so far as to claim she dabbles in witchcraft at home, while others chalk her unusual behavior up to the stress of teaching an unending flow of unruly youngsters.\n\nHaving endured more pain than she's willing to share, Alana keeps to herself, preferring the company of children to that of other adults in the village. Equal parts mysterious, generous, and domineering, she also possesses a whimsy about her, which only reveals itself when she is around her closest confidantes. Get in her good graces, and you'll have her heart. Wrong her, and you'll face indignation that would make even a grizzled auld Scotsman blush.\n\nAbove all, the children under her care are her greatest priority, and she'll do anything to protect them. Even if it means making foes.\n                                "
    new "Nacida y criada en Ach-na-Creige, Alana Urquhart es una figura permanente en la ciudad. La maestra favorita (y única) de todos, es a la vez estricta y cariñosa con los niños y niñas bajo su cuidado. Mientras tanto, las excentricidades de Alana le han dado una reputación extraña entre los antiguos alumnos que han crecido. Algunos llegan incluso a afirmar que se dedica a la brujería en casa, mientras que otros atribuyen su comportamiento inusual al estrés de enseñar a un flujo interminable de jóvenes rebeldes.\n\nHabiendo soportado más dolor del que está dispuesta a compartir, Alana se mantiene reservada, prefiriendo la compañía de los niños a la de otros adultos del pueblo. Misteriosa, generosa y dominante a partes iguales, también posee una extravagancia que sólo se revela cuando está cerca de sus confidentes más cercanos. Gánate su favor y tendrás su corazón. Si le haces daño, te enfrentarás a una indignación que haría sonrojar incluso a un canoso anciano escocés.\n\nPor encima de todo, los niños bajo su cuidado son su mayor prioridad y hará cualquier cosa para protegerlos. Incluso si eso significa ganarse enemigos.\n                                "

    # game/screens_cast.rpy:9120
    old "{i}\"A healthy dose of confusion and contentment? That's love, m'boy!\nEnjoy this while it lasts. It's likely to get worse!\"{/i}\n                                "
    new "{i}\"¿Una saludable dosis de confusión y satisfacción? ¡Eso es amor, muchacho!\nDisfrutalo mientras dure. ¡Es probable que empeore!\"{/i}\n                                "

    # game/screens_cast.rpy:9126
    old "Balgair Buchan is a Scotsman through and through, and a true son of Ach-na-Creige. Born and bred in the tiny lochside hamlet, he's a rough and tumble gent, always ready to provide a firm handshake, a pint, and a good laugh. A trusty companion to all he meets, he'll lend a patient ear for a friend in need.\n\nThe owner and proprietor of the Stag & Nanny has turned the local pub into a night time haunt for jazz music and bawdy flappers. Balgair is a dreamer and a schemer, always on the hunt to find a new way to turn a profit.\n\nThis strong and proud veteran may come across as a little rough around the edges, but Balgair has a heart as soft and warm as a fresh pot of buttered rumbledethumps.\n                                "
    new "Balgair Buchan es un hombre escocés de principio a fin y un verdadero hijo de Ach-na-Creige. Nacido y criado en la pequeña aldea junto al lago, es un caballero rudo y agitado, siempre dispuesto a ofrecer un firme apretón de manos, una pinta y una buena risa. Un compañero confiable para todos los que conoce, siempre prestará un oído paciente a un amigo necesitado.\n\nEl dueño y propietario de Stag & Nanny ha convertido la taberna local en un lugar nocturno para escuchar música jazz y ver a flappers obscenas. Balgair es un soñador y buen planeador, siempre a la caza de encontrar una nueva forma de obtener ganancias.\n\nEste veterano fuerte y orgulloso puede parecer un poco rudo, pero Balgair tiene un corazón igual de suave y cálido como una olla de rumbledethumps recién horneada\n                                "

    # game/screens_cast.rpy:9354
    old "{i}\"There is so little left here. To have you back is a miracle all to itself.\"{/i}\n                                "
    new "{i}\"Queda tan poco aquí. Tenerte de vuelta es un milagro en sí mismo.\"{/i}\n                                "

    # game/screens_cast.rpy:9360
    old "Agnes Campbell grew up in Ach-na-Creige, just as her parents did, and their parents before them. The Scottish Highlands breathe life into this elderly matriarch, who will always remain young-at-heart. When she isn't cooking, cleaning, or waggling a ladle to make a point, she can be found strolling the fields, reading a good book, or, more likely, enjoying a dram of whisky by the fire.\n\nSince losing her husband, Eachann Campbell, Agnes reminisces about the good times shared, and the years spent with her son and daughter-in-law before the arrival of her cherished grandson, Malcolm.\n\nWhile Malcolm was away at war, Agnes watched the village shrink as men left and never returned. Fear and sadness left her all but faded, but reuniting with her grandson has rekindled her spirit. To lose him again would trouble her deeply.\n                                "
    new "Agnes Campbell creció en Ach-na-Creige, tal como lo hicieron sus padres, y los padres de sus padres antes que ellos. Las Tierras Altas de Escocia dan vida a esta anciana matriarca, que siempre será joven de corazón. Cuando no está cocinando, limpiando o moviendo un cucharón para dejar claro algo, se la puede encontrar paseando por los campos, leyendo un buen libro o, más probablemente, disfrutando de un trago de whisky junto al fuego.\n\nDesde que perdió su marido, Eachann Campbell, Agnes recuerda los buenos momentos compartidos y los años que pasó con su hijo y su nuera antes de la llegada de su querido nieto, Malcolm.\n\nMientras Malcolm estaba en la guerra, Agnes observó a la aldea encojerse mientras los hombres se iban y nunca volvieron. El miedo y la tristeza la dejaron casi desvanecida, pero reunirse con su nieto ha reavivado su espíritu. Perderlo de nuevo la preocuparía profundamente.\n                                "

    # game/screens_cast.rpy:9588
    old "{i}\"It won't heal ever, Malcolm. Not when you live through your nightmares. Fall asleep to nightmares, wake to them, and see them when you finally return home.\"{/i}\n                                "
    new "{i}\"No sanará nunca, Malcolm. No cuando vives tus pesadillas. Duérme con las pesadillas, despiérta con ellas y míralas cuando finalmente regreses a casa.\"{/i}\n                                "

    # game/screens_cast.rpy:9594
    old "Owen MacLeod, born in Ach-na-Creige, is part of a family with roots woven right into the tartan of the Highlands. As the eldest child, Owen was raised with the expectation to take over the family farm. His father also worked part time as a village merchant, and his mother wove textiles and linens to sell at market.\n\nMarried at nineteen to his childhood sweetheart, Owen fathered three daughters. The family lived in bliss until the premature death of his wife during childbirth. After this tragedy, Owen thrust himself into his work to make sure his daughters lived in a comfortable—if not a warm—home. In 1914, Owen departed to serve his homeland in the Great War.\n\nWhilst seen by some as a gruff man, those who know him well appreciate his candor, his generosity, and his willingness to help people. He’s also a sharp storyteller, loves baking meat pies, and prides himself as a golfer.\n                                "
    new "Owen MacLeod, nacido en Ach-na-Creige, es parte de una familia con raíces entretejidas en el tartán de las Tierras Altas. Como hijo mayor, Owen fue criado con la expectativa de hacerse cargo de la granja familiar. Su padre también trabajaba a tiempo parcial como comerciante del pueblo, y su madre tejía textiles y ropa de cama para vender en el mercado.\n\nCasado a los diecinueve años con su novia de la infancia, Owen tuvo tres hijas. La familia vivió feliz hasta la muerte prematura de su esposa durante el parto. Después de esta tragedia, Owen se dedicó a trabajar para asegurarse de que sus hijas vivieran en un hogar comodo (aunque tal vez no calido). En 1914, Owen partió para servir a su patria en la Gran Guerra.\n\nAunque algunos lo consideran un hombre brusco, quienes lo conocen bien aprecian su franqueza, su generosidad y su voluntad de ayudar a la gente. También es un gran narrador, le encanta hornear pasteles de carne y se enorgullece de ser golfista.\n                                "

    # game/screens_cast.rpy:9807
    old "{i}\"The sea and her children\nare fickle mistresses.\"{/i}\n                                "
    new "{i}\"El mar y sus hijas\nson amanteS volubles\"{/i}\n                                "

    # game/screens_cast.rpy:9813
    old "Douglas Crannach is a sailor, fisherman, and proud military man. Since returning home from the Great War, he's made it his duty to now serve his local community. He works full-time as the town's fishmonger, providing a solid meal to those who can, and can't, afford one. His mission: to feed the village with the bounty of the loch.\n\nA seafarer through and through, Douglas is no stranger to Poseidon's mysteries. Deeper still, the Crannach family knows all too well about the fae and their trickster nature. Should anything odd appear in Loch Finlay, Douglas will be the first to know, and the first to act.\n\nDouglas may come across as a stodgy lump of old mackerel, but his heart is golden. He simply needs the love of a friend—or perhaps a girlfriend—to give that heart a good polish.\n                                "
    new "Douglas Crannach es un marinero, pescador y orgulloso militar. Desde que regresó a casa después de la Gran Guerra, su deber ahora es servir a su comunidad local. Trabaja a tiempo completo como pescadero de la ciudad, proporcionando una comida sólida a quienes pueden y no pagarla. Su misión: alimentar al pueblo con la generosidad del lago.\n\nMarino de principio a fin, Douglas no es ajeno a los misterios de Poseidón. Más aún, la familia Crannach conoce muy bien a los fae y su naturaleza embaucadora. Si aparece algo extraño en el lago Finlay, Douglas será el primero en enterarse y el primero en actuar.\n\nDouglas puede parecer un duro trozo de caballa vieja, pero su corazón es de oro. Simplemente necesita el amor de un amigo (o tal vez de una novia) para darle un buen brillo a ese corazón.\n                                "
"

    # game/screens_cast.rpy:10067
    old "{i}\"Ah, when you're a traveling entertainer like me, you've seen it all. So-called monsters of all sorts!\"{/i}\n                                "
    new "{i}\"Ah, cuando eres un artista viajero como yo, lo has visto todo.¡Los llamados monstruos de todo tipo!\"{/i}\n                                "

    # game/screens_cast.rpy:10073
    old "Walter is a man of magic. No illusion is too large, no spectacle too small to behold. He is steeped in the world of performance, heralded as the most popular touring entertainer in Northern Scotland. He has performed for everyone from Presidents of the United States to the National Whist Guild of Portland's Oh Pshaw Party.\n\nPreviously, he captured the imagination of young Malcolm and Jessie during a visit to Ach-na-Creige with his traveling circus; a visit, he says, that changed the course of his career. Always by his side is his capuchin monkey, Little Nap, a feisty boy who enjoys eating apples as much as he likes pilfering them out of childrens' pockets.\n\nWalter has his eyes set on Jessie MacLeod, for what illustrious magician doesn't want the most talented seductress alive to be part of his production? Especially if her skills come with a bit of something supernatural on the side...\n                                "
    new "Walter es un hombre de mágia. Ninguna ilusión es demasiado grande, ningún espectáculo es demasiado pequeño para contemplarlo. Está inmerso en el mundo del espectáculo y es considerado el artista itinerante más popular del norte de Escocia. Ha actuado para todos, desde presidentes de los Estados Unidos hasta el Gremio Nacional de Whist del Partido Oh Pshaw de Portland.\n\nAnteriormente, capturó la imaginación de los jóvenes Malcolm y Jessie durante una visita a Ach-na-Creige con su circo ambulante; una visita, que dice, cambió el curso de su carrera. Siempre a su lado está su mono capuchino, Little Nap, un niño luchador que disfruta comiendo manzanas tanto como robandolas de los bolsillos de los niños.\n\nWalter tiene sus ojos puestos en Jessie MacLeod, porque ¿qué mago ilustre no quiere que la seductora más talentosa del mundo sea parte de su producción? Especialmente si sus habilidades vienen con una pizca de algo sobrenatural incluido...\n                                "

